[package]
name = "upstox-rust-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
async-imap = { version = "0.9.7", default-features = false, features = ["runtime-tokio"] }
async-native-tls = { version = "0.5.0", default-features = false, features = ["runtime-tokio"] }
chrono = "0.4.38"
dotenvy = "0.15.7"
fantoccini = "0.19.3"
flate2 = "1.0.30"
futures = "0.3.30"
mailparse = "0.15.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["json"] }
scraper = "0.19.0"
serde = "1.0.203"
serde_json = "1.0.117"
serde_valid = "0.24.0"
serde_with = "3.8.1"
tokio = { version = "1.38.0", features = ["full"] }
tokio-cron-scheduler = { version = "0.10.2", features = ["signal"]}
url_open = "0.0.2"
urlencoding = "2.1.3"
