[package]
name = "uplink-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
async-imap = "0.9.7"
dotenvy = "0.15.7"
fantoccini = "0.19.3"
futures = "0.3.30"
reqwest = { version = "0.12.5", features = ["json"] }
serde = "1.0.203"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
url_open = "0.0.2"
urlencoding = "2.1.3"
